# Generated by Django 3.0.6 on 2020-05-22 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
